server:
  port: 8189
  servlet:
    context-path: /three-oceans.fitness/accounts

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/accountsdb
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

